import type { RaidRoomDefinition } from "./types";

export const RAID_ROOMS: readonly RaidRoomDefinition[] = [
  {
    id: "entry-chamber",
    number: 1,
    name: "Entry Chamber",
    theme: "entry",
    introTitle: "ENTRY CHAMBER",
    introText: "Initial corruption cluster detected. Learn the lane and hold the perimeter.",
    crawlers: 8,
    drones: 0,
    eliteDrones: 0,
    hasReward: true,
  },
  {
    id: "drone-chamber",
    number: 2,
    name: "Drone Chamber",
    theme: "drone",
    introTitle: "DRONE CHAMBER",
    introText: "Ranged defenders online. Break the crossfire before the chamber closes.",
    crawlers: 7,
    drones: 4,
    eliteDrones: 0,
    hasReward: true,
  },
  {
    id: "surge-chamber",
    number: 3,
    name: "Surge Chamber",
    theme: "surge",
    introTitle: "SURGE CHAMBER",
    introText: "System instability rising. Expect faster pressure and elite resistance.",
    crawlers: 9,
    drones: 5,
    eliteDrones: 2,
    hasReward: false,
  },
  {
    id: "boss-chamber",
    number: 4,
    name: "Boss Chamber",
    theme: "boss",
    introTitle: "BOSS CHAMBER",
    introText: "Signal lock complete. The Blackout Core is somewhere in the chamber.",
    crawlers: 0,
    drones: 0,
    eliteDrones: 0,
    hasReward: false,
  },
] as const;
